spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test-db

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console